apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 497346559457.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 497346559457.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e1e77cbd
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
